org: dougui
service: dynamodb-serverless-perfect-duo

package:
  individually: true

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt ProductsTable.Arn

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    format: esm
    target: node24
    platform: node
    exclude:
      - "@aws-sdk/*"
    outExtension:
      ".js": ".mjs"

functions:
  listProducts:
    handler: src/functions/listProducts.handler
    events:
      - httpApi:
          path: /products
          method: get
  getProduct:
    handler: src/functions/getProduct.handler
    events:
      - httpApi:
          path: /products/{id}
          method: get
  createProduct:
    handler: src/functions/createProduct.handler
    events:
      - httpApi:
          path: /products
          method: post
  updateProduct:
    handler: src/functions/updateProduct.handler
    events:
      - httpApi:
          path: /products/{id}
          method: put
  deleteProduct:
    handler: src/functions/deleteProduct.handler
    events:
      - httpApi:
          path: /products/{id}
          method: delete

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
